spring:
  application:
    name: usian-item-service222
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.159.144:8066/usian?characterEncoding=UTF-8
    username: root
    password: 1111
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.159.137:7001
        - 192.168.159.137:7002
        - 192.168.159.137:7003
        - 192.168.159.137:7004
        - 192.168.159.137:7005
        - 192.168.159.137:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.159.129
    username: admin
    password: 1111
    virtual-host: /

#配置缓存首页商品分类的 key
portal_catresult_redis_key: portal_catresult_redis_key
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#商品详情
ITEM_INFO: ITEM_INFO
BASE: BASE
DESC: DESC
PARAM: PARAM
ITEM_INFO_EXPIRE: 86400
SETNX_BASC_LOCK_KEY: SETNX_BASC_LOCK_KEY
SETNX_DESC_LOCK_KEY: SETNX_DESC_LOCK_KEY
